version: '2.1'

services:
  azure_devops_demo:
    image: azure_devops_demo
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js